//
//  AthleteDetailWorker.swift
//  OBSCodingTest
//
//  Created by Shuja MBP on 27/03/2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class AthleteDetailWorker {

    /// Fetches athlete results for the specified athlete ID from the API.
    /// - Parameter id: The ID of the athlete whose results to fetch.
    /// - Returns: An array of `AthleteResultResponse` objects representing the athlete's results.
    func fetchAthleteResults(for id: String) async -> [AthleteResultResponse] {
        let endpoint = GamesEndpoint.atheleteResults(id)

        do {
            let result = try await NetworkLayer.fetch(
                endpoint, with: [AthleteResultResponse].self
            )
            let results: [AthleteResultResponse]
            switch result {
            case .failure(_):
                results = []
            case .success(let models):
                results = models
            }
            return results
        } catch {
            return []
        }
    }
}

