//
//  AthleteDetailPresenter.swift
//  OBSCodingTest
//
//  Created by Shuja MBP on 27/03/2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

/// The presentation logic for displaying an athlete's detail.
protocol AthleteDetailPresentationLogic {

    /**
     Presents an athlete's results.

     - Parameter response: The response containing the athlete's results.
     */
    func presentAthleteResults(response: AthleteDetail.Response)
}

/// The presenter for displaying an athlete's detail.
class AthleteDetailPresenter: AthleteDetailPresentationLogic {

    // MARK: - Properties

    /// The view controller to display the athlete's detail.
    weak var viewController: AthleteDetailDisplayLogic?

    // MARK: - Public Methods

    /**
     Presents an athlete's results on the main thread.

     - Parameter response: The response containing the athlete's results.
     */
    func presentAthleteResults(response: AthleteDetail.Response) {
        DispatchQueue.main.async {
            self.viewController?.displayAthletesResults(
                viewModel: AthleteDetail.ViewModel(
                    results: response.results
                )
            )
        }
    }
}
