//
//  GamesRouter.swift
//  OBSCodingTest
//
//  Created by Shuja MBP on 26/03/2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol GamesRoutingLogic {

    @objc func routeToAthleteDetailWithSegue(_ segue: UIStoryboardSegue)
}

protocol GamesDataPassing {
    var dataStore: GamesDataStore? { get }
}

class GamesRouter: NSObject, GamesRoutingLogic, GamesDataPassing {

    // MARK: - Properties

    weak var viewController: GamesViewController?
    var dataStore: GamesDataStore?

    // MARK: - GamesRoutingLogic

    @objc func routeToAthleteDetailWithSegue(_ segue: UIStoryboardSegue) {
        // Get the destination view controller
        guard let athleteDetail = segue.destination as? AthleteDetailViewController else { return }

        // Pass data to the destination view controller
        var destinationDataStore = athleteDetail.router?.dataStore
        destinationDataStore?.athlete = dataStore?.selectedAthlete
    }
}
